#!/usr/bin/env python3
"""Write the Pages publish-gate middleware from posts.json.

Only registered essays, the index, assets, and a few site meta files may be
served. Everything else is answered 410 Gone.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
POSTS_FILE = ROOT / "posts.json"
MIDDLEWARE_FILE = ROOT / "public" / "functions" / "_middleware.js"
INDEXNOW_KEY_FILE_GLOB = "*.txt"

# Site meta files that are allowed beside essays and /assets/.
ALLOWED_EXACT = (
    "/",
    "/sitemap.xml",
    "/robots.txt",
    "/BingSiteAuth.xml",
)


def load_display_strings(posts_path: Path = POSTS_FILE) -> list[str]:
    """Return ordered unique post path stems from the posts registry."""
    raw: object = json.loads(posts_path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"{posts_path}: root must be a JSON object")
    posts_raw = raw.get("posts")
    if not isinstance(posts_raw, list) or not posts_raw:
        raise ValueError(f"{posts_path}: 'posts' must be a non-empty array")

    ordered: list[str] = []
    seen: set[str] = set()
    for index, item in enumerate(posts_raw):
        if not isinstance(item, dict):
            raise ValueError(f"{posts_path}: posts[{index}] must be an object")
        value = item.get("display_string")
        if value is None:
            value = item.get("slug")
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"{posts_path}: posts[{index}] needs display_string or slug"
            )
        display_string = value.strip()
        if display_string in seen:
            continue
        seen.add(display_string)
        ordered.append(display_string)
    return ordered


def indexnow_key_path(public_dir: Path) -> str | None:
    """Return `/<key>.txt` if exactly one IndexNow key file is present."""
    hex_keys: list[str] = []
    for path in sorted(public_dir.glob(INDEXNOW_KEY_FILE_GLOB)):
        stem = path.stem
        if path.name == "robots.txt":
            continue
        # IndexNow keys are 8–128 hex chars; filename matches body.
        if 8 <= len(stem) <= 128 and all(ch in "0123456789abcdefABCDEF" for ch in stem):
            hex_keys.append(path.name)
    if len(hex_keys) == 1:
        return f"/{hex_keys[0]}"
    return None


def render_middleware(display_strings: list[str], key_path: str | None) -> str:
    """Return `_middleware.js` source for the publish gate."""
    posts_js = json.dumps(display_strings, indent=2)
    allowed: list[str] = list(ALLOWED_EXACT)
    if key_path is not None:
        allowed.append(key_path)
    allowed_js = json.dumps(allowed, indent=2)
    return f"""\
/** Tekmeria publish gate: only site pages; everything else is 410 Gone.
 *
 * Generated by site_cluster/write_publish_gate.py — do not hand-edit.
 * Regenerate via: python site_cluster/site_build_index.py
 */
export async function onRequest(context) {{
  const url = new URL(context.request.url);

  if (url.hostname === "semeia.eulogikon.org") {{
    url.hostname = "tekmeria.eulogikon.org";
    return Response.redirect(url.toString(), 301);
  }}

  let path = url.pathname;
  if (path.length > 1 && path.endsWith("/")) {{
    path = path.slice(0, -1);
  }}
  if (path === "/index.html") {{
    path = "/";
  }}

  const publishedPosts = new Set({posts_js});
  const allowedExact = new Set({allowed_js});

  const isAsset = path.startsWith("/assets/");
  const postStem = path.startsWith("/") ? path.slice(1) : path;
  const isPublishedPost =
    publishedPosts.has(postStem) ||
    (postStem.endsWith(".html") &&
      publishedPosts.has(postStem.slice(0, -".html".length)));

  if (isAsset || allowedExact.has(path) || isPublishedPost) {{
    return context.next();
  }}

  return new Response("Gone", {{
    status: 410,
    headers: {{
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "public, max-age=0, must-revalidate",
    }},
  }});
}}
"""


def write_publish_gate(
    *,
    posts_path: Path = POSTS_FILE,
    middleware_path: Path = MIDDLEWARE_FILE,
    check_only: bool = False,
) -> bool:
    """Write or check the publish-gate middleware. Return True if changed."""
    display_strings = load_display_strings(posts_path)
    public_dir = middleware_path.parent.parent
    key_path = indexnow_key_path(public_dir)
    content = render_middleware(display_strings, key_path)
    if not content.endswith("\n"):
        content += "\n"

    previous = (
        middleware_path.read_text(encoding="utf-8")
        if middleware_path.is_file()
        else None
    )
    changed = previous != content
    if check_only:
        return changed
    if changed:
        middleware_path.parent.mkdir(parents=True, exist_ok=True)
        middleware_path.write_text(content, encoding="utf-8")
    return changed


def main() -> int:
    """CLI: regenerate the publish-gate middleware."""
    changed = write_publish_gate()
    rel = MIDDLEWARE_FILE.relative_to(ROOT.parent)
    if changed:
        print(f"updated {rel}")
    else:
        print(f"{rel} already in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
